/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.academico;

import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-09
 */
public class Ventanaprincipal extends javax.swing.JFrame {

    int arraymenores[] = new int[5];     
    int arraymayores[] = new int[5];
    int viejos[] = new int[5];
    int im=0;
    int ima=0;
    int v=0;
    String muestra="";
    String muestra2="";
    String muestra3="";

    
    public Ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        academicSystem = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        academicSystem.setText("SISTEMA ACADEMICO");

        create.setText("Crear");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        search.setText("Consultar");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(academicSystem)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(academicSystem)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(search))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
            int edad = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Diga su edad papi"));
            if(edad<18){
                if(im<5){
                JOptionPane.showMessageDialog(rootPane, "Usted es menor de edad");
                arraymenores[im]=edad;
                im++;
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se reciben más menores");
                }
            }else if(edad>=18 && edad<60){
                if(ima<5){
                JOptionPane.showMessageDialog(rootPane, "Usted es mayor de edad");                    
                arraymayores[ima]=edad;
                ima++;
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se reciben más mayores");
                }
            }else{
                if(v<5){
                JOptionPane.showMessageDialog(rootPane, "Usted es adulto mayor");                    
                viejos[v]=edad;
                v++;
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se reciben más adultos mayores");
                }
            }
    }//GEN-LAST:event_createActionPerformed
    //ToDo hacer 3 arreglos de 5 slots y que el programa finalice cuando ya estén llenos y en consultar mostrar todo en orden
    
    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        
    }//GEN-LAST:event_createMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        muestra="Edades de los menores registrados:";
        for(int a=0;a<arraymenores.length;a++){
            muestra+="  "+arraymenores[a];
            System.out.println("a:"+a);
            System.out.println(muestra);
        }
        muestra2="Edades de los mayores registrados:";
        for(int a=0;a<arraymayores.length;a++){
            muestra2+="  "+arraymayores[a];
            System.out.println("a:"+a);
            System.out.println(muestra2);
        }
        muestra3="Edades de los adultos mayores registrados:";
        for(int a=0;a<viejos.length;a++){
            muestra3+="  "+viejos[a];
            System.out.println("a:"+a);
            System.out.println(muestra3);
        }
        JOptionPane.showMessageDialog(rootPane, muestra+"\n"+muestra2+"\n"+muestra3);
//        JOptionPane.showMessageDialog(rootPane, muestra2);
//        JOptionPane.showMessageDialog(rootPane, muestra3);
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicSystem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton create;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
